### PR TITLE
ensure deep merge of config

### LINKED ISSUE #1011: Error applying minor version label
Got an error when the workflow had a `minor` label applied

Screen Shot 2022-01-13 at 12 13 55 PM

```
name: Draft Release
on:
    push:
        branches:
            - main
        pull_request:
            types: [opened, reopened, synchronize]

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              with:
                  config-name: release-template.yml
              #   disable-autolabeler: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

```
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
    - title: "🚀 What's new"
      labels:
          - 'PR: New'
    - title: '🏋️ Improvements'
      labels:
          - 'PR: Improvement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'PR: Fix'
exclude-labels:
    - 'PR: No Changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    ## Release Changes

    $CHANGES

```

I have a general question to. If we add a `minor` label to multiple PRs will it continuously bump the version number? Or is it only one bump per release? Thanks

### PR DESCRIPTION
**Pull request by jetersen**
fixes #1011

### CODE REVIEW

**Comment by jetersen** [comment]
@nowsprinting seems we forgot the deep merge part in #973 😅

**Comment by KevinBatdorf** [comment]
Thanks. How can I ensure no one accidentally adds a label that bumps the major version? Would this work as expected?

```
    major:
        labels:
            - ''
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
```

**Comment by jetersen** [comment]
This would still work, that was part of the deep merge fix.

```yaml
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
```

in our code once merged with default it will become:

```yaml
    major:
        labels:
            - ''
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
```

**Comment by nowsprinting** [comment]
@jetersen Thanks!
I didn't expect this issue. sorry.

**Pull request merged**
