### PR TITLE
Add closed Issues to release changelog

### LINKED ISSUE #213: Consider adding closed issues to release
A section where all the issues that were closed after the last release are added.

### PR DESCRIPTION
**Pull request by rohit-gohri**
Closes #213

- [x] Parse PR body for issues
- [ ] Get issues closed by commits directly
- [ ] Get Issue details through API
- [ ] Generate list of issues through template
	- Probably will contain: Issue title, closed by, closed through
- [ ] Add options to enable/disable/customize this in config
- [ ] Add tests

### CODE REVIEW

**Comment by jetersen** [comment]
Parsing PR body seems ill adviced there much exist an GraphQL for doing what `Linked issues` does.

image

**Comment by jetersen** [comment]
Seems possible 😓 Though it is not pretty.
https://github.community/t/get-all-issues-linked-to-a-pull-request/14653/6

**Comment by rohit-gohri** [comment]
Hi, I forgot about this completely.
Linked issues does seem like a better idea. Any idea if it will also have issues mentioned in the commit messages that are part of the PR? That would simplify the flow by a lot. Will have to test this out. 

Though these days I'm using GitLab as part of work so not sure when I'll get time for this. If anyone else wants to take it up feel free.

**Comment by jetersen** [comment]
As there is no official api for this, I am closing the issue.

**Comment by jetersen** [comment]
Seemed they have added `closingIssuesReferences` on the pull request object schema

**Pull request closed without merging**
