### PR TITLE
Add release version to github action output

### LINKED ISSUE #1298: Expose RESOLVED_VERSION As output field for using in the other steps
Hi,
Is it possible to release drafter expose calculated version `$RESOLVED_VERSION` as [action output field](https://github.com/release-drafter/release-drafter#action-outputs)?
I want to this version inner my other steps.
I think it can be added to [existing outputs](https://github.com/release-drafter/release-drafter/blob/ac463ffd9cc4c6ad5682af93dc3e3591c4657ee3/index.js#L268)

### PR DESCRIPTION
**Pull request by mehdihadeli**
fixes #1298

### CODE REVIEW

**Comment by inomn** [comment]
Hi! Any updates on this? :)

**Comment by mehdihadeli** [comment]
I'm waiting for the review :)

**Comment by jetersen** [comment]
Please see the contributions.md and follow the steps to generate dist

**Review by jetersen — APPROVED** [review]
LGTM except for missing dist

**Comment by lemeurherve** [comment]
(nit: "feat" is missing its "t" in the title)

**Comment by jetersen** [comment]
@lemeurherve fixed 😉

**Comment by paulo-hortelan** [comment]
Hi guys, is there any reason on why this hasn't been merged yet? That's exactly what i need

**Comment by jetersen** [comment]
Stilling missing the dist to be updated.

**Comment by mehdihadeli** [comment]
I did a `yarn build` according CONTRIBUTING.md

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
I'll release later today once I get home 😓

**Comment by mehdihadeli** [comment]
Thanks for merging :)

**Comment by jetersen** [comment]
@mehdihadeli I think we missed an update to [action.yml](https://github.com/release-drafter/release-drafter/blob/master/action.yml)
Would you mind sending a PR for the updated outputs? 🙇

**Comment by mehdihadeli** [comment]
@mehdihadeli sure, I will send a new pull request for that

**Pull request merged**
