### PR TITLE
WIP: TypeScript refactor

### PR DESCRIPTION
**Pull request by TimonVS**
I'm often making silly mistakes while implementing new features or fixing bugs. If you don't mind @toolmantim I'll refactor the codebase to TypeScript :)

## Todo

- [x] TypeScript config
- [x] Jest set-up for TypeScript
- [x] Configure ESLint and Prettier for TypeScript
- [ ] Update "Developing" section in README
- [ ] Convert *.js files to *.ts
- [ ] Generate types for GraphQL queries (maybe)

### CODE REVIEW

**Comment by toolmantim** [comment]
Fine with me!

**Comment by casz** [comment]
I'd still like to see this happen 😅

**Comment by TimonVS** [comment]
@casz I will split this PR up some time soon to have TS infrastructure ready so that we can migrate over to TS file by file instead of one big PR.

**Comment by jetersen** [comment]
Closing as I think the base has diverged significantly, better to start over 😅

**Pull request closed without merging**
